In [1]:
import pandas as pd
import numpy as np

In [2]:
l_num = np.arange(0, 10).tolist()

In [3]:
def leer_csv(ruta: str) -> pd.DataFrame:
    df = pd.read_csv(ruta, sep=';', encoding='latin-1', dtype='str')
    df.columns = (df.columns.str.strip()
                  .str.lower()
                  .str.replace(' ', '_')
                  .str.replace('ó', 'o')
                  .str.replace('í', 'i')
                 )
    return df

In [4]:
stock_2019 = leer_csv('../data/raw/stock-2019.csv')
nacimientos_2019 = leer_csv('../data/raw/nacimientos-2019.csv')
muertes_2019 = leer_csv('../data/raw/muertes-2019.csv')

stock_2020 = leer_csv('../data/raw/stock-2020.csv')
nacimientos_2020 = leer_csv('../data/raw/nacimientos-2020.csv')
muertes_2020 = leer_csv('../data/raw/muertes-2020.csv')

stock_2021 = leer_csv('../data/raw/stock-2021.csv')
nacimientos_2021 = leer_csv('../data/raw/nacimientos-2021.csv')
muertes_2021 = leer_csv('../data/raw/muertes-2021.csv')

stock_2022 = leer_csv('../data/raw/stock-2022.csv')
nacimientos_2022 = leer_csv('../data/raw/nacimientos-2022.csv')
muertes_2022 = leer_csv('../data/raw/muertes-2022.csv')

In [5]:
def numero(s:pd.Series) -> pd.Series:
    return pd.to_numeric(s.str.strip().str.replace('.', '')
                         , errors='coerce')

In [6]:
nacimientos_2019['total'] = numero(nacimientos_2019['total'])
muertes_2019['total'] = numero(muertes_2019['total'])
stock_2019['total'] = numero(stock_2019['total'])

nacimientos_2020['total'] = numero(nacimientos_2020['total'])
muertes_2020['total'] = numero(muertes_2020['total'])
stock_2020['total'] = numero(stock_2020['total'])

nacimientos_2021['total'] = numero(nacimientos_2021['total'])
muertes_2021['total'] = numero(muertes_2021['total'])
stock_2021['total'] = numero(stock_2021['total'])

nacimientos_2022['total'] = numero(nacimientos_2022['total'])
muertes_2022['total'] = numero(muertes_2022['total'])
stock_2022['total'] = numero(stock_2022['total'])

In [7]:
nacimientos_2019[nacimientos_2019['comunidades_y_ciudades_autonomas'].isna()]

,total_nacional,comunidades_y_ciudades_autonomas,actividad_principal_(cnae_2009),condicion_juridica,total
0,Total Nacional,NaN,Todas las actividades,Total,365893
1,Total Nacional,NaN,Todas las actividades,Personas físicas,268302
2,Total Nacional,NaN,Todas las actividades,Sociedades Anónimas y R. Limitada,75490
3,Total Nacional,NaN,Todas las actividades,Otras formas,22101
4,Total Nacional,NaN,"05 Extracción de antracita, hulla y lignito",Total,0
...,...,...,...,...,...
323,Total Nacional,NaN,"95 Reparación de ordenadores, efectos persona...",Otras formas,96
324,Total Nacional,NaN,96 Otros servicios personales,Total,18820
325,Total Nacional,NaN,96 Otros servicios personales,Personas físicas,16781
326,Total Nacional,NaN,96 Otros servicios personales,Sociedades Anónimas y R. Limitada,1421
327,Total Nacional,NaN,96 Otros servicios personales,Otras formas,618

In [8]:
# filtrado
def por_actividad(df:pd.DataFrame) -> pd.Series:
    return df[(df['actividad_principal_(cnae_2009)'] != 'Todas las actividades') & (df['condicion_juridica'] == 'Personas físicas') & (df['comunidades_y_ciudades_autonomas'].isna())].set_index('actividad_principal_(cnae_2009)')['total']

In [9]:
dnueve = pd.DataFrame({
    'stock': por_actividad(stock_2019),
    'nacimientos': por_actividad(nacimientos_2019),
    'muertes': por_actividad(muertes_2019),
})

veinte = pd.DataFrame({
    'stock': por_actividad(stock_2020),
    'nacimientos': por_actividad(nacimientos_2020),
    'muertes': por_actividad(muertes_2020),
})

vuno = pd.DataFrame({
    'stock': por_actividad(stock_2021),
    'nacimientos': por_actividad(nacimientos_2021),
    'muertes': por_actividad(muertes_2021),
})

vdos = pd.DataFrame({
    'stock': por_actividad(stock_2022),
    'nacimientos': por_actividad(nacimientos_2022),
    'muertes': por_actividad(muertes_2022),
})

In [10]:
dnueve['t_nacimientos'] = np.round((dnueve['nacimientos'] / dnueve['stock']) * 100, 2)
dnueve['t_muertes'] = np.round((dnueve['muertes'] / dnueve['stock']) * 100, 2)
dnueve ['t_neta'] = dnueve['t_nacimientos'] - dnueve['t_muertes']

veinte['t_nacimientos'] = np.round((veinte['nacimientos'] / veinte['stock']) * 100, 2)
veinte['t_muertes'] = np.round((veinte['muertes'] / veinte['stock']) * 100, 2)
veinte ['t_neta'] = veinte['t_nacimientos'] - veinte['t_muertes']

vuno['t_nacimientos'] = np.round((vuno['nacimientos'] / vuno['stock']) * 100, 2)
vuno['t_muertes'] = np.round((vuno['muertes'] / vuno['stock']) * 100, 2)
vuno ['t_neta'] = vuno['t_nacimientos'] - vuno['t_muertes']

vdos['t_nacimientos'] = np.round((vdos['nacimientos'] / vdos['stock']) * 100, 2)
vdos['t_muertes'] = np.round((vdos['muertes'] / vdos['stock']) * 100, 2)
vdos ['t_neta'] = vdos['t_nacimientos'] - vdos['t_muertes']

In [11]:
vdos

,stock,nacimientos,muertes,t_nacimientos,t_muertes,t_neta
actividad_principal_(cnae_2009),,,,,,
"05 Extracción de antracita, hulla y lignito",0,0,0,NaN,NaN,NaN
06 Extracción de crudo de petróleo y gas natural,0,0,0,NaN,NaN,NaN
07 Extracción de minerales metálicos,0,0,0,NaN,NaN,NaN
08 Otras industrias extractivas,116,3,10,2.59,8.62,-6.03
09 Actividades de apoyo a las industrias extractivas,12,5,2,41.67,16.67,25.00
...,...,...,...,...,...,...
"91 Actividades de bibliotecas, archivos, museos y otras actividades culturales",1961,351,255,17.90,13.00,4.90
92 Actividades de juegos de azar y apuestas,6872,260,679,3.78,9.88,-6.10
"93 Actividades deportivas, recreativas y de entretenimiento",20946,2792,2272,13.33,10.85,2.48
"95 Reparación de ordenadores, efectos personales y artículos de uso doméstico",23453,1829,2816,7.80,12.01,-4.21
96 Otros servicios personales,136930,14795,12812,10.80,9.36,1.44

In [12]:
unido = pd.DataFrame({
    '2019': dnueve['t_neta']
    ,'2020': veinte['t_neta']
    ,'2021': vuno['t_neta']
    ,'2022': vdos['t_neta']
})
    #.set_index('actividad_principal_(cnae_2009)')

In [14]:
unido.to_excel('../data/processed/por_sector.xlsx')